### ISSUE TITLE
CRUD Example

### ISSUE THREAD

**Issue by kosir** [webix-hub/webix-meteor-data#1]
Hi, thanks for this integration! It would be nice, if you could expand it with a simple crud example, I'm not sure how to save data and how to make it reactive.
Thanks in advance for any help! BR

**Comment by mkozhukh** [comment]
Hi, 

Check  https://github.com/webix-hub/webix-meteor-example

**Comment by dandv** [comment]
@kosir: an even easier example, using @mkozhukh's webix-meteor-data proxy: https://github.com/dandv/meteor-webix/tree/master/examples/crud

**Comment by kosir** [comment]
Thanks both!
